# 1. Ensure ~/.dotfiles/shell-startup/bash/env gets run first
. ~/.dotfiles/shell-startup/bash/env

# 2. Prevent it from being run later, since we need to use $BASH_ENV for
# non-login non-interactive shells.
# We don't export it, as we may have a non-login non-interactive shell as
# a child.
BASH_ENV=

# 3. Run ~/.dotfiles/shell-startup/bash/login
. ~/.dotfiles/shell-startup/bash/login

# 4. Run ~/.dotfiles/shell-startup/bash/interactive if this is an interactive
# shell.
if [ "$PS1" ]; then
    . ~/.dotfiles/shell-startup/bash/interactive
fi
