#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

devmon --exec-on-drive 'notify-send \
  -i harddrive "devmon" "Volume \"%l\" mounted" \
  && canberra-gtk-play -i device-added' \
  --exec-on-remove 'notify-send \
  -i hdd_unmount "devmon" "Volume \"%l\" unmounted" \
  && canberra-gtk-play -i device-removed' &
xbindkeys &
displaycal-apply-profiles &
xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
dunst &
remind -z -k'notify-send -t 0 -i dialog-information "Reminder" %s \
  && canberra-gtk-play -i alarm-clock-elapsed &' ~/.reminders &

# disable Caps Lock
setxkbmap -option caps:none
setxkbmap -option c:66:none

while true; do
    slstatus
done &

exec dwm
